In [2]:
import torch

In [5]:
# View
# Returns a new tensor with the same data but of a different shape.
# If you're also concerned about memory usage and want to ensure that the two tensors share the same data use view else reshape.
# Also if you want contiguous memory then use view.
# randn - random in normal distribution
# view - contiguous memory
# reshape - contiguous memory + non contiguous memory

tensor_random = torch.randn(4, 4)

print(tensor_random)
print(tensor_random.shape)

print("-"*20)

tensor_random_view_1 = tensor_random.view(16)
print(tensor_random_view_1)
print(tensor_random_view_1.shape)

print("-"*20)

try:
  tensor_random_view_2 = tensor_random.view(-1, 7)
  print(tensor_random_view_2)
  print(tensor_random_view_2.shape)
except Exception as e :
  print(e)
  tensor_random_view_2 = tensor_random.view(-1, 8)
  print(tensor_random_view_2)
  print(tensor_random_view_2.shape)

print("-"*20)

tensor_random = tensor_random * 100
print(tensor_random)
print(tensor_random_view_1)
print(tensor_random_view_2)

tensor([[-0.9797,  0.0737, -1.2152, -0.3706],
        [ 0.3998, -1.1689, -1.0452,  0.2829],
        [ 0.9545, -0.3216,  0.4582,  0.9806],
        [-0.3928, -1.4732,  0.9353,  0.3828]])
torch.Size([4, 4])
--------------------
tensor([-0.9797,  0.0737, -1.2152, -0.3706,  0.3998, -1.1689, -1.0452,  0.2829,
         0.9545, -0.3216,  0.4582,  0.9806, -0.3928, -1.4732,  0.9353,  0.3828])
torch.Size([16])
--------------------
shape '[-1, 7]' is invalid for input of size 16
tensor([[-0.9797,  0.0737, -1.2152, -0.3706,  0.3998, -1.1689, -1.0452,  0.2829],
        [ 0.9545, -0.3216,  0.4582,  0.9806, -0.3928, -1.4732,  0.9353,  0.3828]])
torch.Size([2, 8])
--------------------
tensor([[ -97.9717,    7.3684, -121.5237,  -37.0575],
        [  39.9756, -116.8865, -104.5227,   28.2937],
        [  95.4488,  -32.1639,   45.8173,   98.0614],
        [ -39.2823, -147.3225,   93.5295,   38.2769]])
tensor([-0.9797,  0.0737, -1.2152, -0.3706,  0.3998, -1.1689, -1.0452,  0.2829,
         0.9545, -0.3216, 

In [4]:
# Reshape - Preffered
# Returns a tensor with the same data and number of elements as input, but with the specified shape.

tensor_random = torch.randn(16)
print(tensor_random)
print(tensor_random.shape)

print("-"*20)

tensor_random_reshape = torch.reshape(tensor_random, (4, 4))
print(tensor_random_reshape)
print(tensor_random_reshape.shape)

print("-"*20)

tensor_random_flatten =  torch.reshape(tensor_random_reshape, (-1,))
print(tensor_random_flatten)
print(tensor_random_flatten.shape)

tensor([ 0.6513, -0.7731, -0.7640,  0.1308,  0.5672,  0.8227,  0.4109,  0.5776,
        -1.2507, -1.3159, -1.8391, -0.9059,  0.4306,  0.1109, -0.0708,  1.9742])
torch.Size([16])
--------------------
tensor([[ 0.6513, -0.7731, -0.7640,  0.1308],
        [ 0.5672,  0.8227,  0.4109,  0.5776],
        [-1.2507, -1.3159, -1.8391, -0.9059],
        [ 0.4306,  0.1109, -0.0708,  1.9742]])
torch.Size([4, 4])
--------------------
tensor([ 0.6513, -0.7731, -0.7640,  0.1308,  0.5672,  0.8227,  0.4109,  0.5776,
        -1.2507, -1.3159, -1.8391, -0.9059,  0.4306,  0.1109, -0.0708,  1.9742])
torch.Size([16])


In [6]:
# Stack

random_stack = torch.randn(2, 3)
print(random_stack)
print(random_stack.shape)

# OR

random_stack = torch.tensor([[ 0.5174, -1.6801, -1.7602],
                             [ 1.2056, -0.1794,  0.9064]])

'''
Shape : 2,3
Rows (dim=0): 2
Columns (dim=1): 3
'''

print("-"*20)

# By Default dimension is 0
print("Dimension 0 or default")
random_stack_dim_default = torch.stack((random_stack, random_stack))
print(random_stack_dim_default)
print(random_stack_dim_default.shape)

print("-"*20)

print("Dimension 0")
random_stack_dim_0 = torch.stack((random_stack, random_stack), dim=0)
print(random_stack_dim_0)
print(random_stack_dim_0.shape)

'''
[        ⬅ New dimension (dim=0, outer)
  [ [0.5174, -1.6801, -1.7602],      ⬅ Original tensor 1
    [1.2056, -0.1794,  0.9064] ],

  [ [0.5174, -1.6801, -1.7602],      ⬅ Original tensor 2
    [1.2056, -0.1794,  0.9064] ]
]

The new dimension is added before the rows
'''

print("-"*20)

print("Dimension 1")
random_stack_dim_1 = torch.stack((random_stack, random_stack), dim=1)
print(random_stack_dim_1)
print(random_stack_dim_1.shape)

'''
[
  [ [0.5174, -1.6801, -1.7602], [0.5174, -1.6801, -1.7602] ],  ⬅ Rows are stacked (dim=1)
  [ [1.2056, -0.1794,  0.9064], [1.2056, -0.1794,  0.9064] ]
]

The new dimension is added between the rows and columns
'''

print("-"*20)

print("Dimension 2") # Results in Tensor Transpose
random_stack_dim_2 = torch.stack((random_stack, random_stack), dim=2)
print(random_stack_dim_2)
print(random_stack_dim_2.shape)

'''
Shape : 2,3
Rows (dim=0): 2
Columns (dim=1): 3

So we are going to insert new dimesnion after column
'''



print("-"*20)

print("Dimension -1") # Results in Tensor Transpose
random_stack_dim_neg_1 = torch.stack((random_stack, random_stack), dim=-1)
print(random_stack_dim_neg_1)
print(random_stack_dim_neg_1.shape)

'''
[
  [ [0.5174, 0.5174], [-1.6801, -1.6801], [-1.7602, -1.7602] ],   ⬅ Columns stacked element-wise (dim=2)
  [ [1.2056, 1.2056], [-0.1794, -0.1794], [ 0.9064,  0.9064] ]
]

The new dimension is added after the columns, so each column is paired element-wise from both tensors
'''



tensor([[ 0.2090,  0.6124, -0.5516],
        [-1.3712,  0.0385, -1.8110]])
torch.Size([2, 3])
--------------------
Dimension 0 or default
tensor([[[ 0.5174, -1.6801, -1.7602],
         [ 1.2056, -0.1794,  0.9064]],

        [[ 0.5174, -1.6801, -1.7602],
         [ 1.2056, -0.1794,  0.9064]]])
torch.Size([2, 2, 3])
--------------------
Dimension 0
tensor([[[ 0.5174, -1.6801, -1.7602],
         [ 1.2056, -0.1794,  0.9064]],

        [[ 0.5174, -1.6801, -1.7602],
         [ 1.2056, -0.1794,  0.9064]]])
torch.Size([2, 2, 3])
--------------------
Dimension 1
tensor([[[ 0.5174, -1.6801, -1.7602],
         [ 0.5174, -1.6801, -1.7602]],

        [[ 1.2056, -0.1794,  0.9064],
         [ 1.2056, -0.1794,  0.9064]]])
torch.Size([2, 2, 3])
--------------------
Dimension 2
tensor([[[ 0.5174,  0.5174],
         [-1.6801, -1.6801],
         [-1.7602, -1.7602]],

        [[ 1.2056,  1.2056],
         [-0.1794, -0.1794],
         [ 0.9064,  0.9064]]])
torch.Size([2, 3, 2])
--------------------
Dimensio

'\n[\n  [ [0.5174, 0.5174], [-1.6801, -1.6801], [-1.7602, -1.7602] ],   ⬅ Columns stacked element-wise (dim=2)\n  [ [1.2056, 1.2056], [-0.1794, -0.1794], [ 0.9064,  0.9064] ]\n]\n\nThe new dimension is added after the columns, so each column is paired element-wise from both tensors\n'

# Building a Simple Linear Regression Model

In [ ]:
import torch.nn as nn

In [ ]:
# Input data (features)
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])

# Output data (targets)
y = torch.tensor([[2.0], [4.0], [6.0], [8.0]])


In [ ]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        # Define the model's parameters
        self.linear = nn.Linear(in_features=1, out_features=1)

    def forward(self, x):
        # Define the forward pass
        out = self.linear(x)
        return out


* class LinearRegressionModel(nn.Module): We create a class that inherits from nn.Module, which is essential for any PyTorch model.
* def __init__(self): The constructor where we define the layers and parameters of our model.
* super().__init__(): Initializes the base class nn.Module.
* self.linear = nn.Linear(in_features=1, out_features=1): A linear layer that applies a linear transformation
𝑦 = 𝑥 ⋅ weight + bias.
* in_features=1: The number of input features (since each input x is a single value).
* out_features=1: The number of output features (predicting a single value).
* def forward(self, x): The forward pass method where computation happens.
* out = self.linear(x): Applies the linear transformation to the input.
* return out: Returns the output.

# Key PyTorch Components
## torch.nn
Contains all the building blocks for neural networks in PyTorch, such as layers, activation functions, and loss functions. It allows you to construct computational graphs, which are sequences of computations executed in a specific order.

## torch.nn.Parameter
A subclass of torch.Tensor that is automatically registered as a parameter when assigned as an attribute to an nn.Module. Parameters are tensors that are considered model parameters, and if requires_grad=True (the default), gradients are automatically computed for them during backpropagation.

## torch.nn.Module
The base class for all neural network modules in PyTorch. It provides a way to encapsulate parameters, helpers for moving them to GPUs, exporting, loading, and more. All custom models should subclass nn.Module and implement the forward() method.

## torch.optim
Contains optimization algorithms (optimizers) used to update the parameters of a model based on the gradients computed during backpropagation. Optimizers adjust the weights to minimize the loss function.

## def forward()
All subclasses of nn.Module must implement the forward() method, which defines how the model processes input data and produces output. This is where the actual computation happens.

In [ ]:
model = LinearRegressionModel()

* model: An instance of our linear regression model.
* The model's parameters (weights and biases) are automatically registered as nn.Parameter objects because they're defined within an nn.Module.

In [ ]:
# Loss function
criterion = nn.MSELoss()

# Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)


* criterion = nn.MSELoss(): The Mean Squared Error loss function, which measures the average squared difference between the predicted and actual values.
* optimizer = torch.optim.SGD(model.parameters(), lr=0.01):
* torch.optim.SGD: The Stochastic Gradient Descent optimizer.
* model.parameters(): Retrieves the model's parameters that need to be updated.
* lr=0.01: The learning rate, controlling how much to adjust the parameters during each update.


In [ ]:
num_epochs = 4

for epoch in range(num_epochs):
    # Forward pass: Compute predicted y
    y_pred = model(X)

    # Compute loss
    loss = criterion(y_pred, y)

    # Zero gradients
    optimizer.zero_grad()

    # Backward pass: Compute gradients
    loss.backward()

    # Update parameters
    optimizer.step()

    # Print progress
    if (epoch+1) % 2 == 0:
        print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}')


Epoch [2/4], Loss: 8.7367
Epoch [4/4], Loss: 4.2290


In [ ]:
print(f"Model weights {model.linear.weight.data}")
print(f"Model bias {model.linear.bias.data}")

* Training Loop: Iterates over the dataset multiple times (epochs) to train the model.
* y_pred = model(X): Performs the forward pass by calling the model on the input data. This invokes the forward() method.
* loss = criterion(y_pred, y): Computes the loss between the predicted values and actual values.
* optimizer.zero_grad(): Clears old gradients before computing new ones.
* loss.backward(): Performs backpropagation to compute gradients of the loss w.r.t. model parameters.
* optimizer.step(): Updates the model parameters using the computed gradients.
* Progress Printing: Every 2 epochs, prints the current loss to monitor training progress.

In [ ]:
# Test the model
with torch.no_grad():  # Disables gradient calculation
    predicted = model(X)
    print(X.ndim)
    print(X.shape)
    print(X.squeeze().shape)
    print('='*20)
    print('Input values: ', X[:,0])
    print('Input values: ', X.squeeze().numpy())
    print('='*20)
    print('Predicted values:', predicted.squeeze().numpy())
    print('='*20)
    print('Actual values:', y.squeeze().numpy())

# torch.squeeze removes dimensions of size 1 from a tensor

2
torch.Size([4, 1])
torch.Size([4])
Input values:  tensor([1., 2., 3., 4.])
Input values:  [1. 2. 3. 4.]
Predicted values: [1.5892568 2.857023  4.124789  5.3925557]
Actual values: [2. 4. 6. 8.]


Understanding Squeeze

In [ ]:
a = torch.tensor([[[3]]])
print(a)
a_new = a.squeeze()
print(a_new)